shallow_clone: false

os:
  - Visual Studio 2017

build:
  verbosity: minimal

configuration:
  - Debug
  - Release

install:
  # Init submodules
  - git submodule init 
  - git submodule update
  
  - cmake --version

before_build:
  - del "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0" /F /Q # Hack: Delete unsupported SDK
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\minomaly

build_script:
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 15 2017"
  - cmake --build . --config %CONFIGURATION%
  - cd ..

test_script:
  - cd bin\%CONFIGURATION%
    # See if the simplest example app runs
  - __template.exe
    # Run MinoTests
  - MinoTest.exe

# Only build interesting files
only_commits:
    files:
        - lib/
        - src/
        - examples/
        - testing/
        - CMakeLists.txt
        - appveyor.yml
